# Generated by Django 5.2.8 on 2025-12-08 18:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(db_index=True, default=True, help_text='Is the record active? (soft delete flag)')),
                ('visible', models.BooleanField(db_index=True, default=True, help_text='Should the record be visible in UI listings?')),
                ('human_id', models.CharField(blank=True, db_index=True, default=None, help_text='Human-readable ID unique within scope', max_length=64, null=True)),
                ('code', models.CharField(db_index=True, help_text='Unique code within scope (e.g., abbreviation)', max_length=64)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('comment', models.TextField(blank=True, default='')),
                ('note', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Production Line',
                'verbose_name_plural': 'Production Lines',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
