# Generated by Django 5.2.8 on 2025-11-25 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productionline', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productionline',
            name='uq_productionline_factory_code',
        ),
        migrations.RemoveField(
            model_name='productionline',
            name='factory',
        ),
    ]
