# Generated by Django 5.2.8 on 2025-12-06 17:04

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carrier', '0001_initial'),
        ('driver', '0001_initial'),
        ('factory', '0003_factory_address_factory_company_and_more'),
        ('location', '0001_initial'),
        ('machine', '0001_initial'),
        ('pit', '0001_initial'),
        ('pot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(db_index=True, default=True, help_text='Is the record active? (soft delete flag)')),
                ('visible', models.BooleanField(db_index=True, default=True, help_text='Should the record be visible in UI listings?')),
                ('dump_date', models.DateField(db_index=True)),
                ('dump_time', models.TimeField(db_index=True)),
                ('pit_number', models.CharField(blank=True, default='', help_text='Číslo jamy (text)', max_length=50)),
                ('pot_side', models.CharField(choices=[('FRONT', 'FRONT'), ('BACK', 'BACK'), ('NONE', 'NONE')], db_index=True, default='NONE', max_length=5)),
                ('pot_knocks', models.PositiveIntegerField(help_text='Počet úderov (0..25). Validované aj voči Pot.knocks_max.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)])),
                ('pot_knocks_measurement', models.PositiveIntegerField(blank=True, help_text='Skutočne nameraný počet úderov pri meraní (0..25)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)])),
                ('pot_weight_kg', models.DecimalField(decimal_places=3, help_text='Weight of the pot (kg)', max_digits=9, validators=[django.core.validators.MinValueValidator(0)])),
                ('roi_temp_max_c', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('roi_temp_mean_c', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('roi_temp_min_c', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('roc_value_min_c', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('roc_value_max_c', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('video_local_file', models.FileField(blank=True, help_text='Lokálna cesta/súbor pre video (uložené v MEDIA_ROOT)', null=True, upload_to='videos/%Y/%m/')),
                ('photo_local_file', models.FileField(blank=True, help_text='Lokálna cesta/súbor pre fotku (uložené v MEDIA_ROOT)', null=True, upload_to='photos/%Y/%m/')),
                ('graph_roc', models.JSONField(blank=True, help_text='Pole bodov čas-hodnota pre ROC graf', null=True)),
                ('graph_temp', models.JSONField(blank=True, help_text='Pole bodov čas-hodnota pre TEMP graf', null=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('note', models.TextField(blank=True, default='')),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='carrier.carrier')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='driver.driver')),
                ('factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='factory.factory')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='location.location')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='machine.machine')),
                ('pit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='pit.pit')),
                ('pot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='pot.pot')),
            ],
            options={
                'verbose_name': 'Measurement',
                'verbose_name_plural': 'Measurements',
                'ordering': ['-dump_date', '-dump_time', '-id'],
                'indexes': [models.Index(fields=['factory', 'dump_date', 'dump_time'], name='measurement_factory_d1b04e_idx'), models.Index(fields=['factory', 'location'], name='measurement_factory_072574_idx'), models.Index(fields=['dump_date', 'dump_time'], name='measurement_dump_da_65ea1e_idx'), models.Index(fields=['pot_side'], name='measurement_pot_sid_f60cfa_idx')],
            },
        ),
    ]
