# Generated by Django 5.2.8 on 2025-12-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text='Unique code within scope (e.g., abbreviation)', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='human_id',
            field=models.CharField(blank=True, db_index=True, default=None, help_text='Human-readable ID unique within scope', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
