# Generated by Django 5.2.8 on 2025-11-25 01:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(db_index=True, default=True, help_text='Is the record active? (soft delete flag)')),
                ('visible', models.BooleanField(db_index=True, default=True, help_text='Should the record be visible in UI listings?')),
                ('human_id', models.CharField(blank=True, db_index=True, default=None, help_text='Human-readable ID unique within scope', max_length=64, null=True)),
                ('code', models.CharField(db_index=True, help_text='Unique code within scope (e.g., abbreviation)', max_length=64)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('comment', models.TextField(blank=True, default='')),
                ('note', models.TextField(blank=True, default='')),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('measured_at', models.DateTimeField(blank=True, null=True)),
                ('measurement_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Measurement',
                'verbose_name_plural': 'Measurements',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(db_index=True, default=True, help_text='Is the record active? (soft delete flag)')),
                ('visible', models.BooleanField(db_index=True, default=True, help_text='Should the record be visible in UI listings?')),
                ('human_id', models.CharField(blank=True, db_index=True, default=None, help_text='Human-readable ID unique within scope', max_length=64, null=True)),
                ('code', models.CharField(db_index=True, help_text='Unique code within scope (e.g., abbreviation)', max_length=64)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('comment', models.TextField(blank=True, default='')),
                ('note', models.TextField(blank=True, default='')),
                ('process_type', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Process',
                'verbose_name_plural': 'Processes',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
