# Generated by Django 5.2.8 on 2025-12-08 18:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(db_index=True, default=True, help_text='Is the record active? (soft delete flag)')),
                ('visible', models.BooleanField(db_index=True, default=True, help_text='Should the record be visible in UI listings?')),
                ('human_id', models.CharField(blank=True, db_index=True, default=None, help_text='Human-readable ID unique within scope', max_length=64, null=True)),
                ('code', models.CharField(db_index=True, help_text='Unique code within scope (e.g., abbreviation)', max_length=64)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('comment', models.TextField(blank=True, default='')),
                ('note', models.TextField(blank=True, default='')),
                ('knocks_max', models.PositiveIntegerField(default=25, help_text='Max. počet úderov/ťuknutí pre tento kotol (0..25)', validators=[django.core.validators.MaxValueValidator(25)])),
                ('weight_nominal_kg', models.DecimalField(blank=True, decimal_places=3, help_text='Voliteľná nominálna hmotnosť kotla (kg)', max_digits=8, null=True)),
                ('factory', models.ForeignKey(blank=True, help_text='Factory this entity belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='factory.factory')),
            ],
            options={
                'verbose_name': 'Pot',
                'verbose_name_plural': 'Pots',
                'ordering': ['name'],
                'abstract': False,
                'indexes': [models.Index(fields=['factory', 'code'], name='pot_pot_factory_310c3b_idx'), models.Index(fields=['factory', 'active'], name='pot_pot_factory_fce506_idx')],
                'constraints': [models.UniqueConstraint(fields=('factory', 'code'), name='uq_pot_factory_code')],
            },
        ),
    ]
