# Generated by Django 5.2.8 on 2025-11-25 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(db_index=True, max_length=500)),
                ('method', models.CharField(db_index=True, max_length=10)),
                ('response_time_ms', models.FloatField(db_index=True)),
                ('status_code', models.IntegerField(db_index=True)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('query_count', models.IntegerField(blank=True, null=True)),
                ('query_time_ms', models.FloatField(blank=True, null=True)),
                ('memory_usage_mb', models.FloatField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Performance Log',
                'verbose_name_plural': 'Performance Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['endpoint', 'timestamp'], name='logging_per_endpoin_c30b8a_idx'), models.Index(fields=['response_time_ms', 'timestamp'], name='logging_per_respons_5b6a89_idx'), models.Index(fields=['status_code', 'timestamp'], name='logging_per_status__15a3a3_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, max_length=10)),
                ('message', models.TextField()),
                ('module', models.CharField(blank=True, default='', max_length=255)),
                ('function', models.CharField(blank=True, default='', max_length=255)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('request_path', models.CharField(blank=True, default='', max_length=500)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'System Log',
                'verbose_name_plural': 'System Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['level', 'timestamp'], name='logging_sys_level_0c1ca4_idx'), models.Index(fields=['user_id', 'timestamp'], name='logging_sys_user_id_6fcc6e_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View')], db_index=True, max_length=10)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('object_id', models.UUIDField()),
                ('model_name', models.CharField(db_index=True, max_length=255)),
                ('field_name', models.CharField(blank=True, default='', max_length=255)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action', 'timestamp'], name='logging_aud_action_fd5b5d_idx'), models.Index(fields=['user_id', 'timestamp'], name='logging_aud_user_id_a1320f_idx'), models.Index(fields=['model_name', 'timestamp'], name='logging_aud_model_n_522733_idx'), models.Index(fields=['content_type', 'object_id'], name='logging_aud_content_513b2c_idx')],
            },
        ),
    ]
