# Generated by Django 5.2.8 on 2025-12-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_options_user_address_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'SuperAdmin'), ('admin', 'Admin'), ('staff', 'Staff'), ('editor', 'Editor'), ('reader', 'Reader'), ('adhoc', 'AdHoc')], default='reader', help_text='Authorization level for the user', max_length=16),
        ),
    ]
