# Generated by Django 5.2.8 on 2025-11-25 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='factory',
            name='uq_factory_company_code',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='company',
        ),
    ]
