# Generated by Django 5.2.8 on 2025-11-25 00:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratorConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(db_index=True, default=True, help_text='Is the record active? (soft delete flag)')),
                ('visible', models.BooleanField(db_index=True, default=True, help_text='Should the record be visible in UI listings?')),
                ('model_name', models.CharField(db_index=True, max_length=255)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('template', models.TextField(blank=True, default='')),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Generator Config',
                'verbose_name_plural': 'Generator Configs',
                'unique_together': {('model_name',)},
            },
        ),
    ]
