# Generated by Django 5.2.8 on 2025-11-25 00:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(db_index=True, default=True, help_text='Is the record active? (soft delete flag)')),
                ('visible', models.BooleanField(db_index=True, default=True, help_text='Should the record be visible in UI listings?')),
                ('source_model', models.CharField(db_index=True, max_length=255)),
                ('target_model', models.CharField(db_index=True, max_length=255)),
                ('relation_type', models.CharField(db_index=True, max_length=64)),
                ('field_name', models.CharField(blank=True, default='', max_length=255)),
                ('related_name', models.CharField(blank=True, default='', max_length=255)),
                ('on_delete', models.CharField(default='PROTECT', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Relation Registry',
                'verbose_name_plural': 'Relation Registries',
                'indexes': [models.Index(fields=['source_model', 'relation_type'], name='relation_re_source__2ba410_idx'), models.Index(fields=['target_model', 'relation_type'], name='relation_re_target__f98edd_idx')],
                'unique_together': {('source_model', 'target_model', 'relation_type')},
            },
        ),
        migrations.CreateModel(
            name='RelationInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(db_index=True, default=True, help_text='Is the record active? (soft delete flag)')),
                ('visible', models.BooleanField(db_index=True, default=True, help_text='Should the record be visible in UI listings?')),
                ('source_object_id', models.UUIDField()),
                ('target_object_id', models.UUIDField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('source_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_sources', to='contenttypes.contenttype')),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_targets', to='contenttypes.contenttype')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='relation.relationregistry')),
            ],
            options={
                'verbose_name': 'Relation Instance',
                'verbose_name_plural': 'Relation Instances',
                'indexes': [models.Index(fields=['source_content_type', 'source_object_id'], name='relation_re_source__20f125_idx'), models.Index(fields=['target_content_type', 'target_object_id'], name='relation_re_target__daf7c2_idx'), models.Index(fields=['relation', 'source_content_type', 'source_object_id'], name='relation_re_relatio_a07dfa_idx')],
                'unique_together': {('relation', 'source_content_type', 'source_object_id', 'target_content_type', 'target_object_id')},
            },
        ),
    ]
