# Generated by Django 5.2.8 on 2025-12-12 12:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationtemplate',
            options={'ordering': ['notification_type'], 'verbose_name': 'Notification Template', 'verbose_name_plural': 'Notification Templates'},
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='scope_aware',
            field=models.BooleanField(default=False, help_text='Is this notification scope-aware (recipients filtered by scope)'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='template_source',
            field=models.CharField(choices=[('database', 'Database Template'), ('file', 'File Template')], default='database', help_text='Where is template stored - in DB or as file', max_length=20),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='variables',
            field=models.JSONField(blank=True, default=list, help_text="List of variables available in template (e.g., ['username', 'email'])"),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, help_text="User-specific notification preferences (e.g., {'login_notification': False})"),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='body',
            field=models.TextField(blank=True, default='', help_text='Body template (for database templates, can use {variables})'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Is this template active'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='name',
            field=models.CharField(db_index=True, help_text='Human-readable template name', max_length=255),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(db_index=True, help_text="Notification type identifier (e.g., 'login_notification')", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='subject',
            field=models.CharField(blank=True, default='', help_text='Subject template (can use {variables})', max_length=255),
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(db_index=True, default=True, help_text='Is the record active? (soft delete flag)')),
                ('visible', models.BooleanField(db_index=True, default=True, help_text='Should the record be visible in UI listings?')),
                ('notification_type', models.CharField(db_index=True, help_text='Type of notification sent', max_length=100)),
                ('recipient_email', models.EmailField(help_text='Email address where notification was sent', max_length=254)),
                ('status', models.CharField(choices=[('sent', 'Sent Successfully'), ('failed', 'Failed to Send'), ('pending', 'Pending')], db_index=True, default='pending', help_text='Status of notification delivery', max_length=20)),
                ('error_message', models.TextField(blank=True, default='', help_text='Error message if sending failed')),
                ('template_used', models.CharField(blank=True, default='', help_text='Template name that was used', max_length=255)),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Context data used for rendering template (for debugging)')),
                ('scope_identifier', models.CharField(blank=True, default='', help_text='Scope identifier if notification was scope-aware', max_length=255)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When was notification actually sent', null=True)),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['notification_type', 'status'], name='notificatio_notific_7435e1_idx'), models.Index(fields=['recipient_email'], name='notificatio_recipie_0c4ad1_idx'), models.Index(fields=['-created'], name='notificatio_created_d02d70_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationMatrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(db_index=True, default=True, help_text='Is the record active? (soft delete flag)')),
                ('visible', models.BooleanField(db_index=True, default=True, help_text='Should the record be visible in UI listings?')),
                ('notification_type', models.CharField(db_index=True, help_text='Notification type identifier (matches NotificationTemplate.notification_type)', max_length=100)),
                ('recipient_type', models.CharField(choices=[('admin', 'Admin (from settings.ADMIN_EMAIL)'), ('user', 'User (from context)'), ('scope_admins', 'Scope Admins (admins in user scope)'), ('custom', 'Custom Email Address'), ('role', 'All Users with Role')], default='admin', help_text='Type of recipient', max_length=50)),
                ('recipient_identifier', models.CharField(blank=True, default='', help_text='Email address (for custom) or role name (for role) or empty (for admin/user)', max_length=255)),
                ('scope_pattern', models.CharField(blank=True, default='', help_text='Scope pattern for filtering recipients (empty = no scope filtering)', max_length=255)),
                ('conditions', models.JSONField(blank=True, default=dict, help_text="Additional conditions for sending (e.g., {'user_role': 'ADMIN'})")),
                ('enabled', models.BooleanField(default=True, help_text='Is this matrix entry active')),
            ],
            options={
                'verbose_name': 'Notification Matrix',
                'verbose_name_plural': 'Notification Matrix',
                'ordering': ['notification_type', 'recipient_type'],
                'indexes': [models.Index(fields=['notification_type', 'enabled'], name='notificatio_notific_b1c168_idx')],
            },
        ),
    ]
