# Generated by Django 5.2.8 on 2025-11-25 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='company',
            name='uq_company_user_code',
        ),
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
    ]
