/*............................................................
    cameraTableConfig.ts

    Camera table configuration for MyTable (config-driven SSOT).
............................................................*/

import type { MyTableConfig } from '@/components/MyTable/MyTableTypes';

export interface Camera {
  id: string;
  uuid?: string;
  code: string;
  name: string;
  human_id?: string;
  comment?: string;
  note?: string;
  tags?: string;
  active: boolean;
  visible?: boolean;
  created: string;
  updated: string;
  factory?: string;
  factory_display_label?: string;
  location?: string;
  location_display_label?: string;
  manufacturer?: string;
  manufacturer_name?: string;
  camera_serie?: string;
  camera_sn?: string;
  purchased_date?: string;
  installed_date?: string;
  fw_number?: string;
  fw_updated_date?: string;
  installation_type?: string;
  ip?: string;
  port?: number;
  port_type?: string;
  protocol?: string;
  http_port?: number;
  rtsp_port?: number;
  channel?: string;
  stream_type?: string;
  resolution?: string;
  video_quality?: string;
  bitrate?: string;
  max_bitrate?: string;
  video_encoding?: string;
  iframe_interval?: number;
  video_path?: string;
  picture_path?: string;
  path_prefix?: string;
  path_suffix?: string;
  settings_payload?: unknown;
  [key: string]: unknown;
}

export const cameraTableConfig: MyTableConfig<Camera> = {
  tableName: 'Cameras',
  apiEndpoint: '/api/cameras/',
  storageKey: 'camerasTable',
  pageHeader: {
    visible: false, // header rendruje wrapper
  },
  pageFooter: {
    visible: false, // footer rendruje wrapper
  },

  // ============================================
  // PARENT ENTITY SELECTION (Hierarchical 2-level)
  // ============================================
  parentHierarchy: [
    {
      field: 'company',
      endpoint: 'companies',
      label: 'Company',
      requiredMessage: 'Create company first'
    },
    {
      field: 'factory',
      endpoint: 'factories',
      label: 'Factory',
      parentField: 'company',
      requiredMessage: 'Create factory first'
    }
  ],

  fieldsMatrix: {
    uuid: {
      type: 'text',
      header: 'UUID',
      size: 120,
      order: 30,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: false,
      editableInline: false,
      editableInAddModal: false,
      sortable: false,
      resizable: true,
    },
    id: {
      type: 'text',
      header: 'ID',
      size: 80,
      order: 40,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: false,
      editableInline: false,
      editableInAddModal: false,
      sortable: true,
      resizable: true,
    },
    human_id: {
      type: 'text',
      header: 'Human ID',
      size: 150,
      order: 50,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: true,
      filterType: 'text',
      editableInEditModal: true,
      editableInline: true,
      sortable: true,
      resizable: true,
    },
    code: {
      type: 'text',
      header: 'Code',
      size: 150,
      order: 60,
      isInColumnPanel: true,
      defaultVisible: true,
      isInFilterPanel: true,
      filterType: 'text',
      editableInEditModal: true,
      editableInline: true,
      sortable: true,
      resizable: true,
      required: true,
    },
    name: {
      type: 'text',
      header: 'Name',
      size: 250,
      order: 70,
      isInColumnPanel: true,
      defaultVisible: true,
      isInFilterPanel: true,
      filterType: 'text',
      editableInEditModal: true,
      editableInline: true,
      sortable: true,
      resizable: true,
      required: true,
    },
    factory_display_label: {
      type: 'text',
      header: 'Factory',
      size: 200,
      order: 75,
      isInColumnPanel: true,
      defaultVisible: true,
      isInFilterPanel: false,
      editableInEditModal: false,
      editableInline: false,
      editableInAddModal: false,
      sortable: false,
      resizable: true,
    },
    location_display_label: {
      type: 'text',
      header: 'Location',
      size: 180,
      order: 76,
      isInColumnPanel: true,
      defaultVisible: true,
      isInFilterPanel: false,
      editableInEditModal: false,
      editableInline: false,
      editableInAddModal: false,
      sortable: false,
      resizable: true,
    },
    active: {
      type: 'boolean',
      header: 'Active',
      size: 100,
      minSize: 80,
      maxSize: 120,
      order: 100,
      isInColumnPanel: true,
      defaultVisible: true,
      isInFilterPanel: true,
      filterType: 'boolean',
      editableInEditModal: true,
      editableInline: true,
      sortable: true,
      resizable: true,
      trueLabel: 'Active',
      falseLabel: 'Inactive',
      style: 'badge',
      quickToggle: false,
    },
    visible: {
      type: 'boolean',
      header: 'Visible',
      size: 100,
      order: 110,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: true,
      filterType: 'boolean',
      editableInEditModal: true,
      editableInline: true,
      sortable: true,
      resizable: true,
      trueLabel: 'Visible',
      falseLabel: 'Hidden',
      style: 'badge',
      quickToggle: false,
    },
    created: {
      type: 'date',
      header: 'Created',
      size: 180,
      order: 200,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: true,
      filterType: 'daterange',
      editableInEditModal: false,
      editableInline: false,
      editableInAddModal: false,
      sortable: true,
      resizable: true,
      format: 'DD.MM.YYYY HH:mm:ss',
    },
    updated: {
      type: 'date',
      header: 'Updated',
      size: 180,
      order: 210,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: true,
      filterType: 'daterange',
      editableInEditModal: false,
      editableInline: false,
      editableInAddModal: false,
      sortable: true,
      resizable: true,
      format: 'DD.MM.YYYY HH:mm:ss',
    },
    comment: {
      type: 'text',
      header: 'Comment',
      size: 200,
      order: 220,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: true,
      editableInline: true,
      sortable: false,
      resizable: true,
      multiline: true,
    },
    note: {
      type: 'text',
      header: 'Note',
      size: 200,
      order: 230,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: true,
      editableInline: true,
      sortable: false,
      resizable: true,
      multiline: true,
    },
    tags: {
      type: 'text',
      header: 'Tags',
      size: 180,
      order: 240,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: true,
      filterType: 'text',
      editableInEditModal: true,
      editableInline: true,
      sortable: false,
      resizable: true,
      multiline: true,
    },
    factory: {
      type: 'text',
      header: 'Factory UUID',
      size: 140,
      order: 300,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: false,
      editableInline: false,
      editableInAddModal: false,
      sortable: false,
      resizable: true,
    },
    location: {
      type: 'text',
      header: 'Location UUID',
      size: 140,
      order: 310,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: false,
      editableInline: false,
      editableInAddModal: false,
      sortable: false,
      resizable: true,
    },
    manufacturer: {
      type: 'text',
      header: 'Manufacturer',
      size: 180,
      order: 400,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: true,
      editableInline: true,
      sortable: false,
      resizable: true,
    },
    manufacturer_name: {
      type: 'text',
      header: 'Manufacturer Name',
      size: 200,
      order: 410,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: true,
      editableInline: true,
      sortable: false,
      resizable: true,
    },
    camera_serie: {
      type: 'text',
      header: 'Camera Serie',
      size: 180,
      order: 420,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: true,
      editableInline: true,
      sortable: false,
      resizable: true,
    },
    camera_sn: {
      type: 'text',
      header: 'Camera SN',
      size: 180,
      order: 430,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: true,
      editableInline: true,
      sortable: false,
      resizable: true,
    },
    purchased_date: {
      type: 'date',
      header: 'Purchased Date',
      size: 160,
      order: 440,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: true,
      editableInline: true,
      sortable: true,
      resizable: true,
      format: 'YYYY-MM-DD',
    },
    installed_date: {
      type: 'date',
      header: 'Installed Date',
      size: 160,
      order: 450,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: true,
      editableInline: true,
      sortable: true,
      resizable: true,
      format: 'YYYY-MM-DD',
    },
    fw_number: {
      type: 'text',
      header: 'FW Number',
      size: 160,
      order: 460,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: true,
      editableInline: true,
      sortable: false,
      resizable: true,
    },
    fw_updated_date: {
      type: 'date',
      header: 'FW Updated',
      size: 160,
      order: 470,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: true,
      editableInline: true,
      sortable: true,
      resizable: true,
      format: 'YYYY-MM-DD',
    },
    installation_type: {
      type: 'text',
      header: 'Installation Type',
      size: 180,
      order: 480,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: true,
      editableInline: true,
      sortable: false,
      resizable: true,
    },
    ip: {
      type: 'text',
      header: 'IP',
      size: 160,
      order: 490,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: true,
      editableInline: true,
      sortable: false,
      resizable: true,
    },
    port: {
      type: 'number',
      header: 'Port',
      size: 120,
      order: 500,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: true,
      editableInline: true,
      sortable: true,
      resizable: true,
    },
    port_type: {
      type: 'text',
      header: 'Port Type',
      size: 150,
      order: 510,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: true,
      editableInline: true,
      sortable: false,
      resizable: true,
    },
    protocol: {
      type: 'text',
      header: 'Protocol',
      size: 140,
      order: 520,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: true,
      editableInline: true,
      sortable: false,
      resizable: true,
    },
    http_port: {
      type: 'number',
      header: 'HTTP Port',
      size: 140,
      order: 530,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: true,
      editableInline: true,
      sortable: true,
      resizable: true,
    },
    rtsp_port: {
      type: 'number',
      header: 'RTSP Port',
      size: 140,
      order: 540,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: true,
      editableInline: true,
      sortable: true,
      resizable: true,
    },
    channel: {
      type: 'text',
      header: 'Channel',
      size: 140,
      order: 550,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: true,
      editableInline: true,
      sortable: false,
      resizable: true,
    },
    stream_type: {
      type: 'text',
      header: 'Stream Type',
      size: 160,
      order: 560,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: true,
      editableInline: true,
      sortable: false,
      resizable: true,
    },
    resolution: {
      type: 'text',
      header: 'Resolution',
      size: 160,
      order: 570,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: true,
      editableInline: true,
      sortable: false,
      resizable: true,
    },
    video_quality: {
      type: 'text',
      header: 'Video Quality',
      size: 170,
      order: 580,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: true,
      editableInline: true,
      sortable: false,
      resizable: true,
    },
    bitrate: {
      type: 'text',
      header: 'Bitrate',
      size: 150,
      order: 590,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: true,
      editableInline: true,
      sortable: false,
      resizable: true,
    },
    max_bitrate: {
      type: 'text',
      header: 'Max Bitrate',
      size: 160,
      order: 600,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: true,
      editableInline: true,
      sortable: false,
      resizable: true,
    },
    video_encoding: {
      type: 'text',
      header: 'Video Encoding',
      size: 170,
      order: 610,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: true,
      editableInline: true,
      sortable: false,
      resizable: true,
    },
    iframe_interval: {
      type: 'number',
      header: 'iFrame Interval',
      size: 160,
      order: 620,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: true,
      editableInline: true,
      sortable: true,
      resizable: true,
    },
    video_path: {
      type: 'text',
      header: 'Video Path',
      size: 200,
      order: 630,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: true,
      editableInline: true,
      sortable: false,
      resizable: true,
    },
    picture_path: {
      type: 'text',
      header: 'Picture Path',
      size: 200,
      order: 640,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: true,
      editableInline: true,
      sortable: false,
      resizable: true,
    },
    path_prefix: {
      type: 'text',
      header: 'Path Prefix',
      size: 200,
      order: 650,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: true,
      editableInline: true,
      sortable: false,
      resizable: true,
    },
    path_suffix: {
      type: 'text',
      header: 'Path Suffix',
      size: 200,
      order: 660,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: true,
      editableInline: true,
      sortable: false,
      resizable: true,
    },
    settings_payload: {
      type: 'text',
      header: 'Settings Payload',
      size: 220,
      order: 670,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: false,
      editableInline: false,
      editableInAddModal: false,
      sortable: false,
      resizable: true,
    },
  },

  headerVisibility: {
    title: true,
    toolbar: true,
    stats: true,
    pagination: true,
  },

  toolbarVisibility: {
    filters: true,
    columns: true,
    compact: false,
    add: true,
    share: false,
    csv: true,
    xlsx: true,
    pdf: false,
    reset: true,
    save: false,
    editAll: false,
    delete: true,
  },

  actions: {
    edit: true,
    delete: true,
    expand: false,
    inlineShare: false,
  },

  rowSelection: {
    enabled: true,
    persistence: false,
  },

  globalSearch: {
    enabled: true,
    placeholder: 'Search cameras by code, name...',
  },

  filters: {
    persistence: true,
  },

  columns: {
    enabled: true,
    persistence: true,
    fields: {},
  },

  pagination: {
    //defaultPageSize: 5,
    //pageSizeOptions: [5, 10, 20, 50, 100],
    custom: true,
    persistence: true,
  },

  multiLine: {
    enabled: false,
    allowToggle: true,
    persistence: true,
  },

  sorting: {
    initialSort: [{ id: 'name', desc: false }],
    persistence: true,
  },

  emptyState: {
    text: 'No cameras found.',
  },

  callbacks: {},
};
