# Generated by Django 5.2.8 on 2025-12-08 18:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(db_index=True, default=True, help_text='Is the record active? (soft delete flag)')),
                ('visible', models.BooleanField(db_index=True, default=True, help_text='Should the record be visible in UI listings?')),
                ('document_ref', models.CharField(help_text='Relative path or identifier of the PDF document.', max_length=1024)),
                ('page_number', models.PositiveIntegerField(default=1, help_text='1-based page number within the PDF document.')),
                ('x', models.FloatField(default=0.0, help_text='Normalized X coordinate within the page (0.0 - 1.0).')),
                ('y', models.FloatField(default=0.0, help_text='Normalized Y coordinate within the page (0.0 - 1.0).')),
                ('width', models.FloatField(default=0.0, help_text='Normalized width within the page (0.0 - 1.0).')),
                ('height', models.FloatField(default=0.0, help_text='Normalized height within the page (0.0 - 1.0).')),
                ('annotation_type', models.CharField(choices=[('text', 'Text'), ('highlight', 'Highlight'), ('rectangle', 'Rectangle'), ('oval', 'Oval'), ('line', 'Line')], default='text', help_text='Type of annotation (text, highlight, rectangle, oval, line).', max_length=32)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Annotation payload (text, style, color, etc.).')),
                ('layer_key', models.CharField(blank=True, default='', help_text='Logical annotation layer identifier (per owner or shared).', max_length=128)),
                ('owner_model_path', models.CharField(blank=True, db_index=True, default='', help_text="Optional owner model path 'app_label.ModelName'.", max_length=255)),
                ('owner_object_id', models.CharField(blank=True, db_index=True, default='', help_text='Optional owner object identifier (string form).', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Optional extra metadata for the annotation.')),
            ],
            options={
                'verbose_name': 'Annotation',
                'verbose_name_plural': 'Annotations',
                'abstract': False,
                'indexes': [models.Index(fields=['document_ref', 'page_number', 'layer_key'], name='pdfviewer_a_documen_1d165e_idx'), models.Index(fields=['owner_model_path', 'owner_object_id'], name='pdfviewer_a_owner_m_4b6700_idx')],
            },
        ),
        migrations.CreateModel(
            name='FocusedView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(db_index=True, default=True, help_text='Is the record active? (soft delete flag)')),
                ('visible', models.BooleanField(db_index=True, default=True, help_text='Should the record be visible in UI listings?')),
                ('document_ref', models.CharField(help_text='Relative path or identifier of the PDF document.', max_length=1024)),
                ('page_number', models.PositiveIntegerField(default=1, help_text='1-based page number within the PDF document.')),
                ('x', models.FloatField(default=0.0, help_text='Normalized X coordinate within the page (0.0 - 1.0).')),
                ('y', models.FloatField(default=0.0, help_text='Normalized Y coordinate within the page (0.0 - 1.0).')),
                ('zoom', models.FloatField(default=1.0, help_text='Initial zoom level for the viewer (e.g. 1.0 = 100%).')),
                ('source_model_path', models.CharField(db_index=True, help_text="Source model path in the form 'app_label.ModelName'.", max_length=255)),
                ('source_object_id', models.CharField(db_index=True, help_text='Identifier of the source object (string form).', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Optional extra configuration for the viewer.')),
            ],
            options={
                'verbose_name': 'Focused view',
                'verbose_name_plural': 'Focused views',
                'abstract': False,
                'indexes': [models.Index(fields=['source_model_path', 'source_object_id'], name='pdfviewer_f_source__fec628_idx'), models.Index(fields=['document_ref', 'page_number'], name='pdfviewer_f_documen_a332cf_idx')],
            },
        ),
    ]
