/*..............................................................
    measurementTableConfig.ts

    Measurement table configuration for MyTable (config-driven SSOT).
..............................................................*/

import type { MyTableConfig } from '@/components/MyTable/MyTableTypes';

export interface Measurement {
  id: string;
  uuid?: string;
  code?: string;
  name?: string;
  human_id?: string;
  comment?: string;
  note?: string;
  tags?: string;
  dump_date?: string;
  dump_time?: string;
  pit_number?: string;
  pot_side?: string;
  pot_knocks?: number;
  pot_knocks_measurement?: number;
  pot_weight_kg?: number;
  roi_temp_max_c?: number;
  roi_temp_mean_c?: number;
  roi_temp_min_c?: number;
  roc_value_min_c?: number;
  roc_value_max_c?: number;
  video_local_file?: string;
  photo_local_file?: string;
  graph_roc?: unknown;
  graph_temp?: unknown;
  active: boolean;
  visible?: boolean;
  created: string;
  updated: string;
  factory?: string;
  factory_display_label?: string;
  location?: string;
  location_display_label?: string;
  carrier?: string;
  carrier_display_label?: string;
  driver?: string;
  driver_display_label?: string;
  pot?: string;
  pot_display_label?: string;
  pit?: string;
  pit_display_label?: string;
  machine?: string;
  machine_display_label?: string;
  [key: string]: unknown;
}

export const measurementTableConfig: MyTableConfig<Measurement> = {
  tableName: 'Measurements',
  apiEndpoint: '/api/measurements/',
  storageKey: 'measurementsTable',
  pageHeader: {
    visible: false, // header rendruje wrapper
  },
  pageFooter: {
    visible: false, // footer rendruje wrapper
  },

  // ============================================
  // PARENT ENTITY SELECTION (Hierarchical 3-level)
  // ============================================
  parentHierarchy: [
    {
      field: 'company',
      endpoint: 'companies',
      label: 'Company',
      requiredMessage: 'Create company first'
    },
    {
      field: 'factory',
      endpoint: 'factories',
      label: 'Factory',
      parentField: 'company',  // Filter factories by selected company
      requiredMessage: 'Create factory first'
    },
    {
      field: 'location',
      endpoint: 'locations',
      label: 'Location',
      parentField: 'factory',  // Filter locations by selected factory
      requiredMessage: 'Create location first'
    }
  ],

  fieldsMatrix: {
    uuid: {
      type: 'text',
      header: 'UUID',
      size: 120,
      order: 30,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: false,
      editableInline: false,
      editableInAddModal: false,
      sortable: false,
      resizable: true,
    },
    
    // Identification fields (inherited from NamedWithCodeModel)
    code: {
      type: 'text',
      header: 'Code',
      size: 100,
      order: 35,
      isInColumnPanel: true,
      defaultVisible: true,
      isInFilterPanel: true,
      editableInEditModal: true,
      editableInline: true,
      editableInAddModal: true,
      required: true,
      sortable: true,
      resizable: true,
    },
    name: {
      type: 'text',
      header: 'Name',
      size: 200,
      order: 36,
      isInColumnPanel: true,
      defaultVisible: true,
      isInFilterPanel: true,
      editableInEditModal: true,
      editableInline: true,
      editableInAddModal: true,
      required: true,
      sortable: true,
      resizable: true,
    },
    human_id: {
      type: 'text',
      header: 'Human ID',
      size: 100,
      order: 37,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: false,
      editableInline: false,
      editableInAddModal: false,
      sortable: true,
      resizable: true,
    },
    
    id: {
      type: 'text',
      header: 'ID',
      size: 100,
      order: 40,
      isInColumnPanel: true,
      defaultVisible: true,
      isInFilterPanel: false,
      editableInEditModal: false,
      editableInline: false,
      editableInAddModal: false,
      sortable: true,
      resizable: true,
    },
    factory_display_label: {
      type: 'text',
      header: 'Factory',
      size: 180,
      order: 50,
      isInColumnPanel: true,
      defaultVisible: true,
      isInFilterPanel: false,
      editableInEditModal: false,
      editableInline: false,
      editableInAddModal: false,
      sortable: false,
      resizable: true,
    },
    location_display_label: {
      type: 'text',
      header: 'Location',
      size: 150,
      order: 60,
      isInColumnPanel: true,
      defaultVisible: true,
      isInFilterPanel: false,
      editableInEditModal: false,
      editableInline: false,
      editableInAddModal: false,
      sortable: false,
      resizable: true,
    },
    carrier_display_label: {
      type: 'text',
      header: 'Carrier',
      size: 150,
      order: 70,
      isInColumnPanel: true,
      defaultVisible: true,
      isInFilterPanel: false,
      editableInEditModal: false,
      editableInline: false,
      editableInAddModal: false,
      sortable: false,
      resizable: true,
    },
    driver_display_label: {
      type: 'text',
      header: 'Driver',
      size: 150,
      order: 80,
      isInColumnPanel: true,
      defaultVisible: true,
      isInFilterPanel: false,
      editableInEditModal: false,
      editableInline: false,
      editableInAddModal: false,
      sortable: false,
      resizable: true,
    },
    pot_display_label: {
      type: 'text',
      header: 'Pot',
      size: 120,
      order: 90,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: false,
      editableInline: false,
      editableInAddModal: false,
      sortable: false,
      resizable: true,
    },
    pit_display_label: {
      type: 'text',
      header: 'Pit',
      size: 120,
      order: 100,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: false,
      editableInline: false,
      editableInAddModal: false,
      sortable: false,
      resizable: true,
    },
    machine_display_label: {
      type: 'text',
      header: 'Machine',
      size: 150,
      order: 110,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: false,
      editableInline: false,
      editableInAddModal: false,
      sortable: false,
      resizable: true,
    },
    
    // FK fields for Add/Edit modals (correct API field names)
    carrier: {
      type: 'fk',
      header: 'Carrier',
      size: 150,
      order: 71,
      isInColumnPanel: false,  // Hidden in table (use display_label instead)
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: true,
      editableInline: false,
      editableInAddModal: true,  // Show in Add modal
      sortable: false,
      resizable: true,
      fkEndpoint: 'carriers',
      required: false,
    },
    driver: {
      type: 'fk',
      header: 'Driver',
      size: 150,
      order: 81,
      isInColumnPanel: false,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: true,
      editableInline: false,
      editableInAddModal: true,
      sortable: false,
      resizable: true,
      fkEndpoint: 'drivers',
      required: false,
    },
    pot: {
      type: 'fk',
      header: 'Pot',
      size: 120,
      order: 91,
      isInColumnPanel: false,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: true,
      editableInline: false,
      editableInAddModal: true,
      sortable: false,
      resizable: true,
      fkEndpoint: 'pots',
      required: false,
    },
    pit: {
      type: 'fk',
      header: 'Pit',
      size: 120,
      order: 101,
      isInColumnPanel: false,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: true,
      editableInline: false,
      editableInAddModal: true,
      sortable: false,
      resizable: true,
      fkEndpoint: 'pits',
      required: false,
    },
    machine: {
      type: 'fk',
      header: 'Machine',
      size: 150,
      order: 111,
      isInColumnPanel: false,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: true,
      editableInline: false,
      editableInAddModal: false,  // NOT in Add modal
      sortable: false,
      resizable: true,
      fkEndpoint: 'machines',
      required: false,
    },
    
    active: {
      type: 'boolean',
      header: 'Active',
      size: 100,
      minSize: 80,
      maxSize: 120,
      order: 150,
      isInColumnPanel: true,
      defaultVisible: true,
      isInFilterPanel: true,
      filterType: 'boolean',
      editableInEditModal: true,
      editableInline: true,
      editableInAddModal: false,  // NOT in Add modal
      sortable: true,
      resizable: true,
      trueLabel: 'Active',
      falseLabel: 'Inactive',
      style: 'badge',
      quickToggle: false,
    },
    visible: {
      type: 'boolean',
      header: 'Visible',
      size: 100,
      order: 160,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: true,
      filterType: 'boolean',
      editableInEditModal: true,
      editableInline: true,
      editableInAddModal: false,  // NOT in Add modal
      sortable: true,
      resizable: true,
      trueLabel: 'Visible',
      falseLabel: 'Hidden',
      style: 'badge',
      quickToggle: false,
    },
    created: {
      type: 'date',
      header: 'Created',
      size: 180,
      order: 200,
      isInColumnPanel: true,
      defaultVisible: true,
      isInFilterPanel: true,
      filterType: 'daterange',
      editableInEditModal: false,
      editableInline: false,
      editableInAddModal: false,
      sortable: true,
      resizable: true,
      format: 'DD.MM.YYYY HH:mm:ss',
    },
    updated: {
      type: 'date',
      header: 'Updated',
      size: 180,
      order: 210,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: true,
      filterType: 'daterange',
      editableInEditModal: false,
      editableInline: false,
      editableInAddModal: false,
      sortable: true,
      resizable: true,
      format: 'DD.MM.YYYY HH:mm:ss',
    },
    comment: {
      type: 'text',
      header: 'Comment',
      size: 200,
      order: 220,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: true,
      editableInline: true,
      editableInAddModal: false,  // NOT in Add modal
      sortable: false,
      resizable: true,
      multiline: true,
    },
    note: {
      type: 'text',
      header: 'Note',
      size: 200,
      order: 230,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: true,
      editableInline: true,
      editableInAddModal: false,  // NOT in Add modal
      sortable: false,
      resizable: true,
      multiline: true,
    },
    tags: {
      type: 'tag',
      header: 'Tags',
      size: 180,
      order: 240,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: true,
      filterType: 'text',
      editableInEditModal: true,
      editableInline: true,
      editableInAddModal: false,  // NOT in Add modal
      sortable: false,
      resizable: true,
    },
    dump_date: {
      type: 'date',
      header: 'Dump Date',
      size: 180,
      order: 300,
      isInColumnPanel: true,
      defaultVisible: true,
      isInFilterPanel: true,
      filterType: 'daterange',
      editableInEditModal: false,
      editableInline: false,
      editableInAddModal: false,
      sortable: true,
      resizable: true,
      format: 'YYYY-MM-DD',
    },
    dump_time: {
      type: 'text',
      header: 'Dump Time',
      size: 140,
      order: 310,
      isInColumnPanel: true,
      defaultVisible: true,
      isInFilterPanel: false,
      editableInEditModal: false,
      editableInline: false,
      editableInAddModal: false,
      sortable: false,
      resizable: true,
    },
    pit_number: {
      type: 'text',
      header: 'Pit Number',
      size: 140,
      order: 320,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: true,
      editableInline: true,
      editableInAddModal: false,  // NOT in Add modal
      sortable: false,
      resizable: true,
    },
    pot_side: {
      type: 'text',
      header: 'Pot Side',
      size: 120,
      order: 330,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: true,
      editableInline: true,
      editableInAddModal: false,  // NOT in Add modal
      sortable: false,
      resizable: true,
    },
    pot_knocks: {
      type: 'number',
      header: 'Pot Knocks',
      size: 140,
      order: 340,
      isInColumnPanel: true,
      defaultVisible: true,
      isInFilterPanel: false,
      editableInEditModal: true,
      editableInline: true,
      editableInAddModal: false,  // NOT in Add modal
      sortable: true,
      resizable: true,
    },
    pot_knocks_measurement: {
      type: 'number',
      header: 'Pot Knocks (Meas.)',
      size: 160,
      order: 350,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: true,
      editableInline: true,
      editableInAddModal: false,  // NOT in Add modal
      sortable: true,
      resizable: true,
    },
    pot_weight_kg: {
      type: 'number',
      header: 'Pot Weight (kg)',
      size: 160,
      order: 360,
      isInColumnPanel: true,
      defaultVisible: true,
      isInFilterPanel: false,
      editableInEditModal: true,
      editableInline: true,
      editableInAddModal: false,  // NOT in Add modal
      sortable: true,
      resizable: true,
    },
    roi_temp_max_c: {
      type: 'number',
      header: 'ROI Temp Max (°C)',
      size: 170,
      order: 370,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: false,
      editableInline: false,
      sortable: true,
      resizable: true,
    },
    roi_temp_mean_c: {
      type: 'number',
      header: 'ROI Temp Mean (°C)',
      size: 170,
      order: 380,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: false,
      editableInline: false,
      sortable: true,
      resizable: true,
    },
    roi_temp_min_c: {
      type: 'number',
      header: 'ROI Temp Min (°C)',
      size: 170,
      order: 390,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: false,
      editableInline: false,
      sortable: true,
      resizable: true,
    },
    roc_value_min_c: {
      type: 'number',
      header: 'ROC Value Min (°C)',
      size: 170,
      order: 400,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: false,
      editableInline: false,
      sortable: true,
      resizable: true,
    },
    roc_value_max_c: {
      type: 'number',
      header: 'ROC Value Max (°C)',
      size: 170,
      order: 410,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: false,
      editableInline: false,
      sortable: true,
      resizable: true,
    },
    video_local_file: {
      type: 'text',
      header: 'Video File',
      size: 220,
      order: 420,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: false,
      editableInline: false,
      editableInAddModal: false,
      sortable: false,
      resizable: true,
    },
    photo_local_file: {
      type: 'text',
      header: 'Photo File',
      size: 220,
      order: 430,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: false,
      editableInline: false,
      editableInAddModal: false,
      sortable: false,
      resizable: true,
    },
    graph_roc: {
      type: 'text',
      header: 'Graph ROC',
      size: 200,
      order: 440,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: false,
      editableInline: false,
      editableInAddModal: false,
      sortable: false,
      resizable: true,
    },
    graph_temp: {
      type: 'text',
      header: 'Graph Temp',
      size: 200,
      order: 450,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: false,
      editableInline: false,
      editableInAddModal: false,
      sortable: false,
      resizable: true,
    },
    factory: {
      type: 'text',
      header: 'Factory UUID',
      size: 140,
      order: 500,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: false,
      editableInline: false,
      editableInAddModal: false,
      sortable: false,
      resizable: true,
    },
    location: {
      type: 'text',
      header: 'Location UUID',
      size: 140,
      order: 510,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: false,
      editableInline: false,
      editableInAddModal: false,
      sortable: false,
      resizable: true,
    },
    carrier: {
      type: 'text',
      header: 'Carrier UUID',
      size: 140,
      order: 520,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: false,
      editableInline: false,
      editableInAddModal: false,
      sortable: false,
      resizable: true,
    },
    driver: {
      type: 'text',
      header: 'Driver UUID',
      size: 140,
      order: 530,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: false,
      editableInline: false,
      editableInAddModal: false,
      sortable: false,
      resizable: true,
    },
    pot: {
      type: 'text',
      header: 'Pot UUID',
      size: 140,
      order: 540,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: false,
      editableInline: false,
      editableInAddModal: false,
      sortable: false,
      resizable: true,
    },
    pit: {
      type: 'text',
      header: 'Pit UUID',
      size: 140,
      order: 550,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: false,
      editableInline: false,
      editableInAddModal: false,
      sortable: false,
      resizable: true,
    },
    machine: {
      type: 'text',
      header: 'Machine UUID',
      size: 140,
      order: 560,
      isInColumnPanel: true,
      defaultVisible: false,
      isInFilterPanel: false,
      editableInEditModal: false,
      editableInline: false,
      editableInAddModal: false,
      sortable: false,
      resizable: true,
    },
  },

  headerVisibility: {
    title: true,
    toolbar: true,
    stats: true,
    pagination: true,
  },

  toolbarVisibility: {
    filters: true,
    columns: true,
    compact: false,
    add: true,
    share: false,
    csv: true,
    xlsx: true,
    pdf: false,
    reset: true,
    save: false,
    editAll: false,
    delete: true,
  },

  actions: {
    edit: true,
    delete: true,
    expand: false,
    inlineShare: false,
  },

  rowSelection: {
    enabled: true,
    persistence: false,
  },

  globalSearch: {
    enabled: true,
    placeholder: 'Search measurements...',
  },

  filters: {
    persistence: true,
  },

  columns: {
    enabled: true,
    persistence: true,
    fields: {},
  },

  pagination: {
    //defaultPageSize: 5,
    //pageSizeOptions: [5, 10, 20, 50, 100],
    custom: true,
    persistence: true,
  },

  multiLine: {
    enabled: false,
    allowToggle: true,
    persistence: true,
  },

  sorting: {
    initialSort: [{ id: 'created', desc: true }],
    persistence: true,
  },

  emptyState: {
    text: 'No measurements found.',
  },

  callbacks: {},

  // MyState - new state management system
  useMyState: true,
};

