# Generated by Django 6.0 on 2025-12-11 22:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(db_index=True, default=True, help_text='Is the record active? (soft delete flag)')),
                ('visible', models.BooleanField(db_index=True, default=True, help_text='Should the record be visible in UI listings?')),
                ('user_id', models.UUIDField(db_index=True, help_text='UUID of the user who owns this preset')),
                ('scope_type', models.CharField(db_index=True, help_text="Type of scope: 'table', 'page', or 'global'", max_length=32)),
                ('scope_key', models.CharField(db_index=True, help_text="Scope identifier, e.g., 'companies', 'dashboard', 'global'", max_length=128)),
                ('preset_name', models.CharField(help_text='User-defined name for this preset', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of this preset')),
                ('state_data', models.JSONField(blank=True, default=dict, help_text='JSON containing the actual state data')),
                ('is_default', models.BooleanField(db_index=True, default=False, help_text='Is this the default preset for this scope?')),
            ],
            options={
                'verbose_name': 'Saved State',
                'verbose_name_plural': 'Saved States',
                'db_table': 'mystate_savedstate',
                'ordering': ['-updated', 'preset_name'],
                'indexes': [models.Index(fields=['user_id', 'scope_type', 'scope_key'], name='mystate_sav_user_id_3c9773_idx'), models.Index(fields=['user_id', 'is_default'], name='mystate_sav_user_id_2a90a3_idx'), models.Index(fields=['scope_type', 'scope_key'], name='mystate_sav_scope_t_1f5923_idx')],
                'unique_together': {('user_id', 'scope_type', 'scope_key', 'preset_name')},
            },
        ),
        migrations.CreateModel(
            name='SharedState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(db_index=True, default=True, help_text='Is the record active? (soft delete flag)')),
                ('visible', models.BooleanField(db_index=True, default=True, help_text='Should the record be visible in UI listings?')),
                ('shared_by_id', models.UUIDField(db_index=True, help_text='UUID of user who shared this preset')),
                ('shared_with_id', models.UUIDField(db_index=True, help_text='UUID of user this preset is shared with')),
                ('can_edit', models.BooleanField(default=False, help_text='Can the recipient edit this preset?')),
                ('source_preset', models.ForeignKey(help_text='The preset being shared', on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='mystate.savedstate')),
            ],
            options={
                'verbose_name': 'Shared State',
                'verbose_name_plural': 'Shared States',
                'db_table': 'mystate_sharedstate',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['shared_with_id'], name='mystate_sha_shared__1d4a30_idx'), models.Index(fields=['shared_by_id'], name='mystate_sha_shared__4b7459_idx')],
                'unique_together': {('source_preset', 'shared_with_id')},
            },
        ),
    ]
