# Generated by Django 5.2.8 on 2025-12-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedstate',
            name='children_state',
            field=models.JSONField(blank=True, default=dict, help_text='Hierarchical snapshot of child scopes. Structure: {scope_type: {preset_name, preset_id, state_data}}'),
        ),
        migrations.AlterField(
            model_name='savedstate',
            name='state_data',
            field=models.JSONField(blank=True, default=dict, help_text="JSON containing this scope's own state data"),
        ),
    ]
