# Generated by Django 5.2.8 on 2025-12-08 18:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StorageConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(db_index=True, default=True, help_text='Is the record active? (soft delete flag)')),
                ('visible', models.BooleanField(db_index=True, default=True, help_text='Should the record be visible in UI listings?')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('storage_type', models.CharField(db_index=True, max_length=50)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Storage Config',
                'verbose_name_plural': 'Storage Configs',
            },
        ),
        migrations.CreateModel(
            name='FileVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(db_index=True, default=True, help_text='Is the record active? (soft delete flag)')),
                ('visible', models.BooleanField(db_index=True, default=True, help_text='Should the record be visible in UI listings?')),
                ('file_path', models.CharField(db_index=True, max_length=1024)),
                ('version', models.IntegerField(default=1)),
                ('file_size', models.BigIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('storage_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_versions', to='file_storage.storageconfig')),
            ],
            options={
                'verbose_name': 'File Version',
                'verbose_name_plural': 'File Versions',
                'ordering': ['-version'],
                'unique_together': {('file_path', 'version')},
            },
        ),
    ]
