# Generated by Django 5.2.8 on 2025-12-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fk_options_cache', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fkoptionscache',
            new_name='fk_options__field_n_c691e1_idx',
            old_name='fk_options__field_n_c06f5b_idx',
        ),
        migrations.RenameIndex(
            model_name='fkoptionscache',
            new_name='fk_options__field_n_d803ae_idx',
            old_name='fk_options__field_n_2a6dd2_idx',
        ),
        migrations.AlterField(
            model_name='cacheconfig',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='cacheconfig',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fkoptionscache',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='fkoptionscache',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
