# Generated by Django 5.2.8 on 2025-12-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='position',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
