# Generated by Django 5.2.8 on 2025-12-08 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('state', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentstate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environment_states', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedworkspace',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_workspaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tablestate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_states', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='environmentstate',
            index=models.Index(fields=['user', 'environment_name', 'is_active'], name='state_envir_user_id_7ade1b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='environmentstate',
            unique_together={('user', 'environment_name')},
        ),
        migrations.AddIndex(
            model_name='savedworkspace',
            index=models.Index(fields=['user', 'is_default'], name='state_saved_user_id_f4208d_idx'),
        ),
        migrations.AddIndex(
            model_name='tablestate',
            index=models.Index(fields=['user', 'table_name', 'is_active'], name='state_table_user_id_46bd96_idx'),
        ),
    ]
