# Generated by Django 5.2.8 on 2025-11-25 00:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(db_index=True, default=True, help_text='Is the record active? (soft delete flag)')),
                ('visible', models.BooleanField(db_index=True, default=True, help_text='Should the record be visible in UI listings?')),
                ('environment_name', models.CharField(db_index=True, max_length=255)),
                ('environment_data', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Environment State',
                'verbose_name_plural': 'Environment States',
            },
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='user',
        ),
    ]
