# Generated by Django 5.2.8 on 2025-11-25 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0003_environmentstate_remove_userpreference_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentstate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environment_states', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserPreference',
        ),
        migrations.AddIndex(
            model_name='environmentstate',
            index=models.Index(fields=['user', 'environment_name', 'is_active'], name='state_envir_user_id_7ade1b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='environmentstate',
            unique_together={('user', 'environment_name')},
        ),
    ]
