# Generated by Django 5.2.8 on 2025-12-08 18:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(db_index=True, default=True, help_text='Is the record active? (soft delete flag)')),
                ('visible', models.BooleanField(db_index=True, default=True, help_text='Should the record be visible in UI listings?')),
                ('human_id', models.CharField(blank=True, db_index=True, default=None, help_text='Human-readable ID unique within scope', max_length=64, null=True)),
                ('code', models.CharField(db_index=True, help_text='Unique code within scope (e.g., abbreviation)', max_length=64)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('comment', models.TextField(blank=True, default='')),
                ('note', models.TextField(blank=True, default='')),
                ('manufacturer', models.CharField(blank=True, default='', max_length=128)),
                ('manufacturer_name', models.CharField(blank=True, default='', max_length=128)),
                ('camera_serie', models.CharField(blank=True, default='', max_length=128)),
                ('camera_sn', models.CharField(blank=True, default='', max_length=128)),
                ('purchased_date', models.DateField(blank=True, null=True)),
                ('installed_date', models.DateField(blank=True, null=True)),
                ('fw_number', models.CharField(blank=True, default='', max_length=128)),
                ('fw_updated_date', models.DateField(blank=True, null=True)),
                ('installation_type', models.CharField(blank=True, default='', max_length=64)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('port', models.PositiveIntegerField(default=0)),
                ('port_type', models.CharField(blank=True, default='', max_length=32)),
                ('protocol', models.CharField(blank=True, default='', max_length=32)),
                ('http_port', models.PositiveIntegerField(default=0)),
                ('rtsp_port', models.PositiveIntegerField(default=0)),
                ('channel', models.CharField(blank=True, default='', max_length=64)),
                ('stream_type', models.CharField(blank=True, default='', max_length=64)),
                ('resolution', models.CharField(blank=True, default='', max_length=64)),
                ('video_quality', models.CharField(blank=True, default='', max_length=64)),
                ('bitrate', models.CharField(blank=True, default='', max_length=64)),
                ('max_bitrate', models.CharField(blank=True, default='', max_length=64)),
                ('video_encoding', models.CharField(blank=True, default='', max_length=64)),
                ('iframe_interval', models.PositiveIntegerField(blank=True, null=True)),
                ('video_path', models.CharField(blank=True, default='', max_length=255)),
                ('picture_path', models.CharField(blank=True, default='', max_length=255)),
                ('path_prefix', models.CharField(blank=True, default='', max_length=255)),
                ('path_suffix', models.CharField(blank=True, default='', max_length=255)),
                ('settings_payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Camera',
                'verbose_name_plural': 'Cameras',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(db_index=True, default=True, help_text='Is the record active? (soft delete flag)')),
                ('visible', models.BooleanField(db_index=True, default=True, help_text='Should the record be visible in UI listings?')),
                ('username', models.CharField(blank=True, default='', max_length=128)),
                ('password', models.CharField(blank=True, default='', max_length=256)),
                ('api_key', models.CharField(blank=True, default='', max_length=256)),
                ('auth_token', models.CharField(blank=True, default='', max_length=512)),
                ('certificate_path', models.CharField(blank=True, default='', max_length=255)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service Credential',
                'verbose_name_plural': 'Service Credentials',
            },
        ),
    ]
