# Generated by Django 5.2.8 on 2025-12-08 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camera', '0001_initial'),
        ('factory', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='factory',
            field=models.ForeignKey(blank=True, help_text='Factory this entity belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='factory.factory'),
        ),
        migrations.AddField(
            model_name='camera',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Location within factory (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='location.location'),
        ),
        migrations.AddField(
            model_name='servicecredential',
            name='camera',
            field=models.OneToOneField(help_text='Camera this credential belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='camera.camera'),
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['factory', 'code'], name='camera_came_factory_43f7ec_idx'),
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['factory', 'active'], name='camera_came_factory_dba1d0_idx'),
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['factory', 'location'], name='camera_came_factory_00cc3d_idx'),
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['ip'], name='camera_came_ip_73599e_idx'),
        ),
        migrations.AddConstraint(
            model_name='camera',
            constraint=models.UniqueConstraint(fields=('factory', 'code'), name='uq_camera_factory_code'),
        ),
    ]
