# Generated by Django 6.0 on 2025-12-11 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='camera',
            name='uq_camera_factory_code',
        ),
    ]
