# Generated by Django 5.2.8 on 2025-12-08 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carrier', '0001_initial'),
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='factory',
            field=models.ForeignKey(blank=True, help_text='Factory this entity belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='factory.factory'),
        ),
        migrations.AddIndex(
            model_name='carrier',
            index=models.Index(fields=['factory', 'code'], name='carrier_car_factory_eef434_idx'),
        ),
        migrations.AddIndex(
            model_name='carrier',
            index=models.Index(fields=['factory', 'active'], name='carrier_car_factory_b8d7d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='carrier',
            constraint=models.UniqueConstraint(fields=('factory', 'code'), name='uq_carrier_factory_code'),
        ),
    ]
