# Generated by Django 5.2.8 on 2025-12-08 18:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(db_index=True, default=True, help_text='Is the record active? (soft delete flag)')),
                ('visible', models.BooleanField(db_index=True, default=True, help_text='Should the record be visible in UI listings?')),
                ('human_id', models.CharField(blank=True, db_index=True, default=None, help_text='Human-readable ID unique within scope', max_length=64, null=True)),
                ('code', models.CharField(db_index=True, help_text='Unique code within scope (e.g., abbreviation)', max_length=64)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('comment', models.TextField(blank=True, default='')),
                ('note', models.TextField(blank=True, default='')),
                ('address', models.CharField(blank=True, default='', help_text='Factory address', max_length=255)),
                ('company', models.ForeignKey(blank=True, help_text='Company that owns this entity', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='company.company')),
            ],
            options={
                'verbose_name': 'Factory',
                'verbose_name_plural': 'Factories',
                'ordering': ['name'],
                'abstract': False,
                'indexes': [models.Index(fields=['company', 'code'], name='factory_fac_company_c71237_idx'), models.Index(fields=['company', 'name'], name='factory_fac_company_a81884_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'code'), name='uq_factory_company_code'), models.UniqueConstraint(condition=models.Q(('human_id__isnull', False)), fields=('human_id',), name='uq_factory_human_id')],
            },
        ),
    ]
