# Generated by Django 5.2.8 on 2025-12-06 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_usercompany_company_users_and_more'),
        ('factory', '0002_remove_factory_uq_factory_company_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='address',
            field=models.CharField(blank=True, default='', help_text='Factory address', max_length=255),
        ),
        migrations.AddField(
            model_name='factory',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company that owns this entity', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='company.company'),
        ),
        migrations.AddIndex(
            model_name='factory',
            index=models.Index(fields=['company', 'code'], name='factory_fac_company_c71237_idx'),
        ),
        migrations.AddIndex(
            model_name='factory',
            index=models.Index(fields=['company', 'name'], name='factory_fac_company_a81884_idx'),
        ),
        migrations.AddConstraint(
            model_name='factory',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uq_factory_company_code'),
        ),
        migrations.AddConstraint(
            model_name='factory',
            constraint=models.UniqueConstraint(condition=models.Q(('human_id__isnull', False)), fields=('human_id',), name='uq_factory_human_id'),
        ),
    ]
