# Generated by Django 5.2.8 on 2025-12-08 18:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(db_index=True, default=True, help_text='Is the record active? (soft delete flag)')),
                ('visible', models.BooleanField(db_index=True, default=True, help_text='Should the record be visible in UI listings?')),
                ('photo_url', models.URLField(blank=True, default='')),
                ('thumbnail_url', models.URLField(blank=True, default='')),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('file_size', models.BigIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('measurement', models.ForeignKey(blank=True, help_text='Measurement this entity belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='measurement.measurement')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'abstract': False,
                'indexes': [models.Index(fields=['measurement'], name='photo_photo_measure_19bb82_idx')],
            },
        ),
    ]
