# Generated by Django 5.2.8 on 2025-12-06 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Photo', 'verbose_name_plural': 'Photos'},
        ),
        migrations.RemoveField(
            model_name='photo',
            name='code',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='human_id',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='note',
        ),
        migrations.AddField(
            model_name='photo',
            name='measurement',
            field=models.ForeignKey(blank=True, help_text='Measurement this entity belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='measurement.measurement'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['measurement'], name='photo_photo_measure_19bb82_idx'),
        ),
    ]
